# codemagic.yaml
workflows:
  web-release: # Workflow 이름 (원하는 대로 변경 가능)
    name: Flutter Web Release Build and Deploy
    instance_type: mac_mini_m1 # 빌드 머신 타입 (필요시 변경)
    max_build_duration: 60 # 최대 빌드 시간 (분)
    environment:
      flutter: stable # 사용할 Flutter 버전 (stable, beta, specific version)
      # 모든 사용 그룹 정의
      groups:
        - google_service_account # 서비스 계정 JSON 키 (Base64 인코딩) 저장용
        - firebase_credentials # Firebase 프로젝트 ID 저장용
        - backend_url # 백엔드 URL 저장용
      # vars: # 일반 (비보안) 변수가 필요하다면 여기에 정의
      #   SOME_VAR: some_value
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Build Flutter web app
        script: |
          # 그룹 통해 변수 참조
          flutter build web --release --dart-define=BACKEND_URL=$backend_url.BACKEND_URL 
    artifacts:
      - build/web/** # 빌드 결과물 경로
    publishing:
      # Firebase Hosting 배포 설정 (서비스 계정 사용)
      firebase:
        # 그룹 통해 변수 참조
        project: $firebase_credentials.FIREBASE_PROJECT_ID
        # 서비스 계정 인증 정보 사용 (그룹 통해 참조)
        google_credentials: $google_service_account.GOOGLE_CREDENTIALS
        # channel: live # 배포 채널 (선택 사항, 예: 'live', 'beta')
