name: polish_learning_app
description: "A new Flutter project for learning Polish."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0' # Adjust based on your Flutter SDK version

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Add core packages
  http: ^1.2.1 # Or latest version
  flutter_riverpod: ^2.5.1 # Or latest version
  hive: ^2.2.3 # Or latest version
  hive_flutter: ^1.1.0 # Or latest version
  path_provider: ^2.0.11 # Example version
  flutter_tts: ^4.0.2 # Use the specific version if known, or a range
  intl: ^0.19.0 # Add intl package
  shared_preferences: ^2.0.15 # Example version
  number_to_words_english: ^2.1.1 # English number words
  russian_words: ^0.2.0 # Replace with Russian words package
  url_launcher: ^6.0.12 # Example version
  sqflite: ^2.0.3 # Example version
  audioplayers: ^6.0.0 

  # Add other packages here if needed, e.g., cupertino_icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
